// Seeded from granola meetings data. Tasks live UNDER initiatives.
window.ROADMAP_DATA = (() => {
  const today = new Date('2026-04-22');
  const D = (s) => s; // ISO date strings

  const PEOPLE = {
    KP: { name: 'Katie P.', initials: 'KP' },
    LB: { name: 'Leann B.', initials: 'LB' },
    LM: { name: 'Lisa M.',  initials: 'LM' },
    HJ: { name: 'Hajar J.', initials: 'HJ' },
    RT: { name: 'Robert T.',initials: 'RT' },
    CR: { name: 'Christina R.', initials: 'CR' },
    NR: { name: 'Nicole R.',initials: 'NR' },
    DG: { name: 'Daniel G.',initials: 'DG' },
    GA: { name: 'Georgia A.', initials: 'GA' },
    MG: { name: 'Mora G.',  initials: 'MG' },
  };

  const initiatives = [
    {
      id: 'init-shopify',
      name: 'Shopify Rollout — 50 Stores',
      thesis: 'Migrate the next wave of campus stores to Shopify with PIM, Pipe 17 and Talent One operating end-to-end.',
      department: 'Rev Ops',
      owner: 'HJ', collaborators: ['RT','CR'],
      priority: 'High',
      status: 'On Track',
      start: '2026-03-15', end: '2026-07-31',
      progress: 0.62,
      health: 'on-track',
      milestones: [
        { date: '2026-04-28', label: 'PIM go-live (first stores)', kind: 'launch' },
        { date: '2026-05-12', label: '50-store wave launch', kind: 'launch' },
        { date: '2026-05-17', label: 'Cincinnati + Pipe 17',  kind: 'event' },
      ],
      tasks: [
        { id:'t-shop-1', title:'Catalog standardization w/ P3',     status:'In Progress', owner:'CR', due:'2026-04-26', priority:'High' },
        { id:'t-shop-2', title:'POS scan recovery — Wheaton UAT',  status:'Blocked', owner:'HJ', due:'2026-04-24', priority:'High' },
        { id:'t-shop-3', title:'Vendor PIM ingest (250+)',          status:'In Progress', owner:'RT', due:'2026-04-28', priority:'High' },
        { id:'t-shop-4', title:'Roles-based access beta release',   status:'Not Started', owner:'HJ', due:'2026-05-02', priority:'Medium' },
        { id:'t-shop-5', title:'Pre/post launch KPI deep-dive',     status:'Not Started', owner:'NR', due:'2026-05-15', priority:'Medium' },
        { id:'t-shop-6', title:'Operational handover requirements', status:'In Progress', owner:'RT', due:'2026-05-08', priority:'Medium' },
      ],
    },
    {
      id: 'init-loyalty',
      name: 'Loyalty Program Launch',
      thesis: 'Stand up the new loyalty program across Shopify-aligned stores — ride the rollout, not race it.',
      department: 'Rev Ops',
      owner: 'RT', collaborators: ['HJ','LB'],
      priority: 'High',
      status: 'At Risk',
      start: '2026-03-01', end: '2026-08-30',
      progress: 0.32,
      health: 'at-risk',
      milestones: [
        { date: '2026-04-28', label: 'Two-store pilot live', kind: 'launch' },
        { date: '2026-06-15', label: 'Loyalty Mgr starts',  kind: 'team' },
        { date: '2026-08-30', label: 'Full rollout',        kind: 'launch' },
      ],
      tasks: [
        { id:'t-loy-1', title:'Resolve Shopify POS interface blockers', status:'Blocked', owner:'HJ', due:'2026-04-25', priority:'High' },
        { id:'t-loy-2', title:'Loyalty manager candidate (Tyler S.)',   status:'In Progress', owner:'RT', due:'2026-04-30', priority:'High' },
        { id:'t-loy-3', title:'Wheaton UAT redemption testing',         status:'In Progress', owner:'HJ', due:'2026-04-26', priority:'Medium' },
        { id:'t-loy-4', title:'Single-university build vs multi',       status:'Not Started', owner:'RT', due:'2026-05-04', priority:'Medium' },
      ],
    },
    {
      id: 'init-slack',
      name: 'Slack Rollout — Field Org',
      thesis: 'Replace email + survey sprawl with Slack as the operating layer for stores and field leadership.',
      department: 'Rev Ops',
      owner: 'KP', collaborators: ['LB'],
      priority: 'High',
      status: 'On Track',
      start: '2026-03-20', end: '2026-05-30',
      progress: 0.71,
      health: 'on-track',
      milestones: [
        { date: '2026-04-21', label: 'Town hall reveal',       kind: 'event' },
        { date: '2026-04-24', label: 'First lunch & learn',    kind: 'event' },
        { date: '2026-05-01', label: 'All teams onboarded',    kind: 'launch' },
      ],
      tasks: [
        { id:'t-slk-1', title:'Rewrite #help channel for mobile',     status:'In Progress', owner:'KP', due:'2026-04-25', priority:'High' },
        { id:'t-slk-2', title:'Field leadership announce (Brian)',    status:'Completed', owner:'KP', due:'2026-04-20', priority:'High' },
        { id:'t-slk-3', title:'L&D orientation slack content',        status:'Not Started', owner:'LB', due:'2026-05-05', priority:'Medium' },
        { id:'t-slk-4', title:'RM success metrics framework',         status:'Not Started', owner:'MG', due:'2026-05-10', priority:'Low' },
        { id:'t-slk-5', title:'Mod squad onboarding workflow',        status:'Blocked', owner:'KP', due:'2026-04-28', priority:'Medium' },
      ],
    },
    {
      id: 'init-esp',
      name: 'ESP Migration (Oracle → New)',
      thesis: 'Replace Oracle Responsys before the January contract end. Marketing-led RFP, top 3 finalists.',
      department: 'Rev Ops',
      owner: 'NR', collaborators: ['LB'],
      priority: 'High',
      status: 'On Track',
      start: '2026-04-01', end: '2027-01-15',
      progress: 0.18,
      health: 'on-track',
      suggestedMilestones: [
        { date: '2026-05-22', label: 'Bloomreach final demo', kind: 'event', source: 'Granola · 4/22 ESP sync', context: "let's lock the final demo date for Bloomreach — week of 5/18" },
        { date: '2026-07-15', label: 'Contract signed', kind: 'decision', source: 'Slack · #esp-rfp', context: 'targeting contract sig by mid-July so we can start parallel run on time' },
      ],
      milestones: [
        { date: '2026-06-30', label: 'Vendor selected',     kind: 'decision' },
        { date: '2026-10-01', label: 'Parallel run begins', kind: 'launch' },
        { date: '2027-01-15', label: 'Oracle sunset',       kind: 'launch' },
      ],
      tasks: [
        { id:'t-esp-1', title:'Top-3 vendor demos',                status:'In Progress', owner:'NR', due:'2026-05-20', priority:'High' },
        { id:'t-esp-2', title:'Use case scoring rubric',           status:'In Progress', owner:'LB', due:'2026-05-05', priority:'Medium' },
        { id:'t-esp-3', title:'Bloomreach point-solution review',  status:'Not Started', owner:'NR', due:'2026-05-30', priority:'Medium' },
      ],
    },
    {
      id: 'init-grad',
      name: 'Grad Appreciation Campaign',
      thesis: 'Convert grad fairs into the highest-margin GM moment of Q2 with a coordinated cross-channel push.',
      department: 'B2C Marketing',
      owner: 'GA', collaborators: ['LM'],
      priority: 'High',
      status: 'On Track',
      start: '2026-04-05', end: '2026-05-25',
      progress: 0.55,
      health: 'on-track',
      milestones: [
        { date: '2026-04-23', label: 'Grad Appreciation Day',  kind: 'event' },
        { date: '2026-05-15', label: 'Diploma frame peak',     kind: 'event' },
      ],
      tasks: [
        { id:'t-grd-1', title:'Email + SMS sends (week of 4/21)', status:'Completed', owner:'GA', due:'2026-04-22', priority:'High' },
        { id:'t-grd-2', title:'Diploma frame promo creative',     status:'In Progress', owner:'LM', due:'2026-04-23', priority:'High' },
        { id:'t-grd-3', title:'14 grad fairs this week',          status:'In Progress', owner:'GA', due:'2026-04-26', priority:'High' },
        { id:'t-grd-4', title:'Iowa best-practice writeup',       status:'Not Started', owner:'LM', due:'2026-05-02', priority:'Low' },
      ],
    },
    {
      id: 'init-esports',
      name: 'Chalked Cast Esports Invitational',
      thesis: 'Plant a flag in collegiate esports with Shopify Rebellion — 16 schools, scholarships, brand reach.',
      department: 'B2B Marketing',
      owner: 'GA', collaborators: ['CR'],
      priority: 'Medium',
      status: 'On Track',
      start: '2026-04-08', end: '2026-05-05',
      progress: 0.44,
      health: 'on-track',
      milestones: [
        { date: '2026-04-30', label: 'Press release',     kind: 'event' },
        { date: '2026-05-02', label: 'Tournament begins', kind: 'launch' },
      ],
      tasks: [
        { id:'t-esp-1a', title:'Scholarship terms + legal',      status:'Blocked', owner:'GA', due:'2026-04-25', priority:'High' },
        { id:'t-esp-2b', title:'Press release draft',            status:'In Progress', owner:'GA', due:'2026-04-28', priority:'High' },
        { id:'t-esp-3c', title:'Social amplification kit',       status:'Not Started', owner:'CR', due:'2026-04-29', priority:'Medium' },
      ],
    },
    {
      id: 'init-transitions',
      name: 'School Transitions — Spring Cohort',
      thesis: 'Onboard Northwestern, Penn State and San Jose State to Follett with a repeatable kickoff playbook.',
      department: 'B2B Marketing',
      owner: 'GA', collaborators: ['LM','KP'],
      priority: 'High',
      status: 'On Track',
      start: '2026-03-25', end: '2026-08-15',
      progress: 0.40,
      health: 'on-track',
      milestones: [
        { date: '2026-04-29', label: 'Northwestern in-person kickoff', kind: 'event' },
        { date: '2026-06-10', label: 'Penn State store open',          kind: 'launch' },
        { date: '2026-08-12', label: 'San Jose State open',            kind: 'launch' },
      ],
      tasks: [
        { id:'t-tr-1', title:'Northwestern kickoff prep',         status:'In Progress', owner:'GA', due:'2026-04-28', priority:'High' },
        { id:'t-tr-2', title:'Penn State campus comms plan',      status:'Not Started', owner:'LM', due:'2026-05-15', priority:'Medium' },
        { id:'t-tr-3', title:'San Jose State requirements doc',   status:'In Progress', owner:'GA', due:'2026-05-08', priority:'High' },
        { id:'t-tr-4', title:'Press release timing playbook',     status:'Not Started', owner:'KP', due:'2026-05-22', priority:'Low' },
      ],
    },
    {
      id: 'init-klt',
      name: 'KLT Annual Meeting',
      thesis: 'Plan the 234-person KLT offsite — speakers, venue, CEO awards, and a customer panel that lands.',
      department: 'All Marketing',
      owner: 'LM', collaborators: ['LB'],
      priority: 'Medium',
      status: 'On Track',
      start: '2026-04-10', end: '2026-09-20',
      progress: 0.25,
      health: 'on-track',
      suggestedMilestones: [
        { date: '2026-08-20', label: 'Save-the-date sent', kind: 'event', source: 'Granola · KLT planning', context: 'we should send save-the-dates ~30 days out from KLT Day 1' },
      ],
      milestones: [
        { date: '2026-04-25', label: 'Speaker shortlist → Manuel', kind: 'decision' },
        { date: '2026-06-30', label: 'Venue locked',               kind: 'decision' },
        { date: '2026-09-18', label: 'KLT Day 1',                   kind: 'event' },
      ],
      tasks: [
        { id:'t-klt-1', title:'Brianna Decker availability',      status:'In Progress', owner:'LM', due:'2026-04-25', priority:'High' },
        { id:'t-klt-2', title:'Drake Hotel buffet decision',      status:'Blocked', owner:'LM', due:'2026-04-28', priority:'Medium' },
        { id:'t-klt-3', title:'Customer panel referral list',     status:'Not Started', owner:'LM', due:'2026-05-10', priority:'Medium' },
        { id:'t-klt-4', title:'CEO Awards run-of-show',           status:'Not Started', owner:'LB', due:'2026-06-15', priority:'Low' },
      ],
    },
    {
      id: 'init-cab',
      name: 'Community College Advisory Board',
      thesis: 'Use the 9-college CAB to validate the dual-enrollment, student access and career pathways pillars.',
      department: 'B2B Marketing',
      owner: 'LM', collaborators: ['GA'],
      priority: 'Medium',
      status: 'On Track',
      start: '2026-04-12', end: '2026-05-15',
      progress: 0.6,
      health: 'on-track',
      milestones: [
        { date: '2026-04-29', label: 'CAB meeting (12–2pm, 9 colleges)', kind: 'event' },
      ],
      tasks: [
        { id:'t-cab-1', title:'Refine sample questions',          status:'In Progress', owner:'LM', due:'2026-04-25', priority:'High' },
        { id:'t-cab-2', title:'Pre-meeting comm (Alex sends)',    status:'Not Started', owner:'LM', due:'2026-04-27', priority:'High' },
        { id:'t-cab-3', title:'Gift shipments coordinated',       status:'In Progress', owner:'LM', due:'2026-04-26', priority:'Medium' },
      ],
    },
    {
      id: 'init-ar',
      name: 'AR Data + CFO Email Recovery',
      thesis: 'Stop the bleeding from the bad AR list, then build a clean CFO record that survives the next handoff.',
      department: 'Rev Ops',
      owner: 'LB', collaborators: ['KP'],
      priority: 'High',
      status: 'At Risk',
      start: '2026-04-15', end: '2026-06-30',
      progress: 0.28,
      health: 'at-risk',
      milestones: [
        { date: '2026-05-10', label: 'Majia AR system live',     kind: 'launch' },
        { date: '2026-06-30', label: 'Semi-annual verify cycle', kind: 'event' },
      ],
      tasks: [
        { id:'t-ar-1', title:'Bounce-back purge in HubSpot',      status:'In Progress', owner:'KP', due:'2026-04-24', priority:'High' },
        { id:'t-ar-2', title:'CFO list handover to Laurie',       status:'Not Started', owner:'LB', due:'2026-04-26', priority:'High' },
        { id:'t-ar-3', title:'Field AR contact verification',     status:'Not Started', owner:'LB', due:'2026-05-15', priority:'Medium' },
      ],
    },
    {
      id: 'init-smd',
      name: 'SMD + Social Expansion',
      thesis: 'Take the Student Marketing Director program to the top 75 and double down on YouTube + creator commissions.',
      department: 'B2C Marketing',
      owner: 'GA', collaborators: ['CR'],
      priority: 'Medium',
      status: 'On Track',
      start: '2026-04-01', end: '2026-09-30',
      progress: 0.35,
      health: 'on-track',
      milestones: [
        { date: '2026-05-30', label: '12 SMDs hired',           kind: 'team' },
        { date: '2026-06-15', label: 'YouTube pilot live',      kind: 'launch' },
        { date: '2026-08-15', label: 'Top-75 expansion approved', kind: 'decision' },
      ],
      tasks: [
        { id:'t-smd-1', title:'Fill 5 open SMD roles',             status:'In Progress', owner:'GA', due:'2026-05-15', priority:'High' },
        { id:'t-smd-2', title:'Growy vs Social Snowball demo',     status:'Blocked', owner:'CR', due:'2026-04-30', priority:'Medium' },
        { id:'t-smd-3', title:'TCU creator commission pilot',      status:'Not Started', owner:'GA', due:'2026-06-01', priority:'Medium' },
      ],
    },
    {
      id: 'init-rental',
      name: 'FY27 Rental Strategy',
      thesis: 'Re-price rental against the ebook market, fix the shelf-tag system, get fall execution to 90%+.',
      department: 'B2B Marketing',
      owner: 'LM', collaborators: ['CR'],
      priority: 'Medium',
      status: 'On Track',
      start: '2026-04-15', end: '2026-08-30',
      progress: 0.20,
      health: 'on-track',
      milestones: [
        { date: '2026-06-01', label: 'Shelf tag redesign locked', kind: 'decision' },
        { date: '2026-07-15', label: '130-store pilot expansion', kind: 'launch' },
      ],
      tasks: [
        { id:'t-rnt-1', title:'Pricing tiers approved',          status:'In Progress', owner:'LM', due:'2026-05-12', priority:'High' },
        { id:'t-rnt-2', title:'Shelf tag legibility audit',      status:'Not Started', owner:'CR', due:'2026-05-20', priority:'Medium' },
        { id:'t-rnt-3', title:'Historical coverage benchmarks',  status:'In Progress', owner:'LM', due:'2026-04-30', priority:'Medium' },
      ],
    },
  ];

  // Inbox tasks — not yet attached to any initiative.
  // These are the kind of things that come in via email/Slack and live in the existing task list.
  const inboxTasks = [
    { id:'in-1',  title:'Refund University of Miami $3.6M double payment', department:'Rev Ops',         priority:'High',   status:'In Progress',       owner:'LB', due:'2026-04-26', source:'email' },
    { id:'in-2',  title:'Review Tony\'s finance letter draft + clean list',  department:'Rev Ops',        priority:'High',   status:'Blocked', owner:'KP', due:'2026-04-24', source:'email' },
    { id:'in-3',  title:'Demo Revenue Vision product (Friday)',              department:'Rev Ops',         priority:'Medium', status:'Not Started',       owner:'RT', due:'2026-04-25', source:'manual' },
    { id:'in-4',  title:'Architecture review for BI platform',               department:'Rev Ops',         priority:'Medium', status:'Not Started',       owner:'RT', due:'2026-04-28', source:'manual' },
    { id:'in-5',  title:'Service policy recommendations to smaller group',   department:'Rev Ops',        priority:'Medium', status:'In Progress',       owner:'LB', due:'2026-04-30', source:'slack' },
    { id:'in-6',  title:'Engagement survey EC personalized notes',           department:'All Marketing',  priority:'Low',    status:'Not Started',       owner:'LM', due:'2026-04-27', source:'manual' },
    { id:'in-7',  title:'Wake Forest tennis hot market miscommunication',    department:'B2C Marketing',  priority:'Medium', status:'In Progress',       owner:'GA', due:'2026-04-23', source:'slack' },
    { id:'in-8',  title:'NYU labor practices protest — comms response',      department:'All Marketing',  priority:'High',   status:'Blocked', owner:'LM', due:'2026-04-23', source:'email' },
    { id:'in-9',  title:'South Carolina store relocation (Rally House)',     department:'B2B Marketing',  priority:'Medium', status:'Not Started',       owner:'GA', due:'2026-05-08', source:'manual' },
    { id:'in-10', title:'Provide 2yr/4yr designation for partner survey',    department:'B2B Marketing',  priority:'Low',    status:'In Progress',       owner:'MG', due:'2026-04-30', source:'manual' },
    { id:'in-11', title:'Claude desktop access for marketing team',          department:'Rev Ops',         priority:'Low',    status:'In Progress',       owner:'LB', due:'2026-04-24', source:'slack' },
    { id:'in-12', title:'Loyalty stakeholder mtg w/ Shopify/P3/Talon One',  department:'Rev Ops',         priority:'High',   status:'Completed',         owner:'HJ', due:'2026-04-17', source:'manual', completedAt:'2026-04-17' },
  ];

  return { initiatives, inboxTasks, people: PEOPLE, today: today.toISOString().slice(0,10), notes: [], suggestedTasks: [] };
})();

// Notes seed at end so it can reference initiative ids above
window.ROADMAP_NOTES_PATCH = (() => {
  const N = (initId, source, author, when, body, badges=[]) => ({
    id: initId+'-n-'+Math.random().toString(36).slice(2,7),
    initiativeId: initId, source, author, when, body, badges,
  });
  const notes = [
    N('init-shopify','granola','HJ','2026-04-19 09:30',
      'Standup: Wheaton POS scan recovery still blocked on P3 catalog standardization. RT flagged this could slip the 5/12 wave. Christina to follow up with P3 by Wed.',
      ['blocker','5/12 wave']),
    N('init-shopify','slack','RT','2026-04-21 14:12',
      'Heads up — Pipe 17 ingest hit 200 of 250 vendors. Last 50 are missing PIM data. Will need vendor outreach this week.',
      ['vendor outreach']),
    N('init-shopify','manual','KP','2026-04-22 11:05',
      'CFO asked for a one-pager on the Shopify rollout for the EC meeting next week. Need rollout timeline + 5/12 wave detail.',
      ['EC meeting','one-pager']),
    N('init-loyalty','granola','RT','2026-04-17 15:00',
      'Loyalty stakeholder mtg w/ Shopify, P3, Talon One. POS interface blockers identified. Tyler S. (loyalty manager candidate) interview confirmed for next week.',
      ['POS blockers','hire']),
    N('init-loyalty','slack','HJ','2026-04-21 10:45',
      'Wheaton UAT: redemption flow works for tier 1 but tier 2/3 throwing errors. Filed ticket with Talon One.',
      ['UAT']),
    N('init-slack','manual','KP','2026-04-20 16:30',
      'Town hall reveal landed well. Brian sent the field announce. Next: rewrite #help channel for mobile usage.',
      ['town hall']),
    N('init-slack','granola','LB','2026-04-22 13:00',
      'L&D orientation: 3 store managers asked for Slack training. Suggest a recurring lunch & learn.',
      ['training']),
    N('init-grad','slack','GA','2026-04-22 09:15',
      '14 grad fairs this week — Iowa team has a great booth setup, asking if we can document for others.',
      ['grad fairs']),
    N('init-ar','manual','LB','2026-04-22 10:00',
      'Bounce-back purge in HubSpot uncovered 1,200 bad records. Need to verify with field reps before deletion.',
      ['data hygiene']),
  ];
  const suggested = [
    { id:'sug-1', initiativeId:'init-shopify', title:'Vendor outreach for last 50 PIM-missing vendors', source:'slack', sourceNote:'init-shopify', sourceQuote:'Last 50 are missing PIM data. Will need vendor outreach this week.', owner:'RT', priority:'High', confidence: 0.88 },
    { id:'sug-2', initiativeId:'init-shopify', title:'Draft one-pager for EC meeting on Shopify rollout', source:'manual', sourceNote:'init-shopify', sourceQuote:'CFO asked for a one-pager… Need rollout timeline + 5/12 wave detail.', owner:'KP', priority:'High', confidence: 0.92 },
    { id:'sug-3', initiativeId:'init-shopify', title:'Follow up with P3 on catalog standardization', source:'granola', sourceNote:'init-shopify', sourceQuote:'Wheaton POS scan recovery still blocked on P3 catalog standardization.', owner:'CR', priority:'High', confidence: 0.81 },
    { id:'sug-4', initiativeId:'init-loyalty', title:'File Talon One ticket for tier 2/3 redemption errors', source:'slack', sourceNote:'init-loyalty', sourceQuote:'tier 2/3 throwing errors. Filed ticket with Talon One.', owner:'HJ', priority:'Medium', confidence: 0.75 },
    { id:'sug-5', initiativeId:'init-slack', title:'Schedule recurring Slack lunch & learn for store managers', source:'granola', sourceNote:'init-slack', sourceQuote:'3 store managers asked for Slack training. Suggest a recurring lunch & learn.', owner:'LB', priority:'Medium', confidence: 0.79 },
    { id:'sug-6', initiativeId:'init-grad', title:'Document Iowa grad-fair booth setup as best-practice', source:'slack', sourceNote:'init-grad', sourceQuote:'Iowa team has a great booth setup, asking if we can document for others.', owner:'LM', priority:'Low', confidence: 0.72 },
  ];
  window.ROADMAP_DATA.notes = notes;
  window.ROADMAP_DATA.suggestedTasks = suggested;
  return true;
})();
